databases:
  TRI:
    url: https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years-1987-2017
    queries:
      TRI_year_reported: 'option'
      TRI_zip: 'value'
  RCRAInfo:
    url: https://rcrapublic.epa.gov/rcra-public-export
    queries:
      Table_of_tables: "//table[@id='tables']"
  eGRID:
    url: https://www.epa.gov/egrid/emissions-generation-resource-integrated-database-egrid
    '2014':
        file_name: 'eGRID2014_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2016':
        file_name: 'egrid2016_data.xlsx'
        file_version: ''
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2018':
        file_name: 'eGRID2018_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-03/egrid2018_data_v2.xlsx'        
  NEI:
    url: 'http://eis.epa.gov'
    '2011':
        file_name:
            - 'NEI/2011NEIv3_R1-3/emis_sum_proc_5906.csv'
            - 'NEI/2011NEIv3_R4-6/emis_sum_proc_5907.csv'
            - 'NEI/2011NEIv3_R7-10/emis_sum_proc_5908.csv'
        file_version: 'v3'
    '2014':
        file_name:
            - 'NEI/2014_NEI_V2_R1-3/emis_sum_proc_6033.csv'
            - 'NEI/2014_NEI_V2_R4-6/emis_sum_proc_6034.csv'
            - 'NEI/2014_NEI_V2_R7-10/emis_sum_proc_6035.csv'
        file_version: 'v2'
    '2016':
        file_name:
            - '../NEI/2016_NEI_R1-3/emis_sum_proc_5828.csv'
            - '../NEI/2016_NEI_R4-6/emis_sum_proc_5829.csv'
            - '../NEI/2016_NEI_R7-10/emis_sum_proc_5830.csv'
        file_version: ''
    '2017':
        file_name: 
            - 'sppd_rtr_13595.csv'
            - 'sppd_rtr_13597.csv'
            - 'sppd_rtr_13602.csv'
        file_version: 'v1'
    national_url: 'ftp://newftp.epa.gov/air/nei/__year__/data_summaries/__version___facility.zip'
    national_version:
        '2017': '2017v1/2017neiApr'
        '2014': '2014v2/2014neiv2'
        '2011': '2011v2/2011neiv2'

